/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Driver para o sqlServer
    implementation("net.sourceforge.jtds:jtds:1.3.1")
    // Driver para o mySql -- Vou tentar adicionar ele
    implementation("com.mysql:mysql-connector-j:9.7.0")
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = "21"
    modules(
        "javafx.controls",
        "javafx.fxml",
        "javafx.graphics",
        "javafx.base",
        // "javafx.media",
        // "javafx.web",
        // "javafx.swing"
    )
}

application {
    // Define the main class for the application.
    mainClass = "edu.fatec.poo.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.named<JavaExec>("run") {
    notCompatibleWithConfigurationCache(
        "O plugin JavaFx 0.1.0 ainda nào suporta ConfigurationCache nesta versão do Gradle"
    )
}